### ISSUE TITLE
Following steps after I downloaded the npm and Node.js

### ISSUE THREAD

**Issue by ghost** [mvasilkov/systematize#17]
I‘m a noob but fond of Mac system font so I download the latest release but I have no idea what should I do next.

I tried to input `npm install —save systematize` in terminal but got this:`⸨░░░░░░░░░░░░░░░░░░⸩ ⠇ rollbackFailedOptional: verb npm-session 5b64df302bdd24b`
) and font didn’t change to SF when I open websites on safari. It’s likely that I missed or totally misunderstand sth.

**Comment by mvasilkov** [comment]
Hi, you use it as follows:

* In the `<head>` of your web page, link to the prebuilt CSS file, `systematize.[min.]css`, found in the [build/](https://github.com/mvasilkov/systematize/tree/master/build) directory.
* Alternatively, use SCSS imports, if your project has the toolchain.

Just to be clear, this is meant for web developers, and has nothing to do with the end user.
